const data_2023 = {
    SecondaryVotesTotalPlusOthers : 1516291,
    Parties : [ 
        {Partyname: "SPD", SecondaryVotes : 278978, SeatsWonDirectly : 4, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 19746, SeatsWonDirectly : 0}, 
            {DistrictNumber: "02", SecondaryVotes : 15683, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 30475, SeatsWonDirectly : 1},
            {DistrictNumber: "04", SecondaryVotes : 29231, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 19001, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 30595, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 29411, SeatsWonDirectly : 1},
            {DistrictNumber: "08", SecondaryVotes : 23535, SeatsWonDirectly : 1},
            {DistrictNumber: "09", SecondaryVotes : 23445, SeatsWonDirectly : 1},
            {DistrictNumber: "10", SecondaryVotes : 17487, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 18868, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 21501, SeatsWonDirectly : 0}]},
        {Partyname: "CDU", SecondaryVotes : 428100, SeatsWonDirectly : 48, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 24131, SeatsWonDirectly : 2},
            {DistrictNumber: "02", SecondaryVotes : 14316, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 40474, SeatsWonDirectly : 3},
            {DistrictNumber: "04", SecondaryVotes : 43135, SeatsWonDirectly : 6},
            {DistrictNumber: "05", SecondaryVotes : 34519, SeatsWonDirectly : 5},
            {DistrictNumber: "06", SecondaryVotes : 53571, SeatsWonDirectly : 7},
            {DistrictNumber: "07", SecondaryVotes : 45940, SeatsWonDirectly : 4},
            {DistrictNumber: "08", SecondaryVotes : 31094, SeatsWonDirectly : 3},
            {DistrictNumber: "09", SecondaryVotes : 33912, SeatsWonDirectly : 4},
            {DistrictNumber: "10", SecondaryVotes : 34889, SeatsWonDirectly : 4},
            {DistrictNumber: "11", SecondaryVotes : 29510, SeatsWonDirectly : 4},
            {DistrictNumber: "12", SecondaryVotes : 42609, SeatsWonDirectly : 6},]},
        {Partyname: "Grüne", SecondaryVotes : 278873, SeatsWonDirectly : 20, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 32424, SeatsWonDirectly : 5},
            {DistrictNumber: "02", SecondaryVotes : 35905, SeatsWonDirectly : 5},
            {DistrictNumber: "03", SecondaryVotes : 42421, SeatsWonDirectly : 5},
            {DistrictNumber: "04", SecondaryVotes : 30419, SeatsWonDirectly : 1},
            {DistrictNumber: "05", SecondaryVotes : 8928, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 27886, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 32100, SeatsWonDirectly : 2},
            {DistrictNumber: "08", SecondaryVotes : 20507, SeatsWonDirectly : 2},
            {DistrictNumber: "09", SecondaryVotes : 15930, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 6053, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 13609, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 12691, SeatsWonDirectly : 0},]},
        {Partyname: "Linke", SecondaryVotes : 184954, SeatsWonDirectly : 4, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 18907, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 22558, SeatsWonDirectly : 1},
            {DistrictNumber: "03", SecondaryVotes : 30460, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 10832, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 3989, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 8316, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 12566, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 14522, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 20672, SeatsWonDirectly : 1},
            {DistrictNumber: "10", SecondaryVotes : 15801, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 21526, SeatsWonDirectly : 2},
            {DistrictNumber: "12", SecondaryVotes : 4805, SeatsWonDirectly : 0},]},
        {Partyname: "AfD", SecondaryVotes : 137810, SeatsWonDirectly : 2, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 6720, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 3940, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 17965, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 7439, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 9709, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 8664, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 9259, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 8324, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 18078, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 21002, SeatsWonDirectly : 2},
            {DistrictNumber: "11", SecondaryVotes : 16082, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 10628, SeatsWonDirectly : 0},]},
        {Partyname: "FDP", SecondaryVotes : 70416, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 6062, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 3552, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 7359, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 10326, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 4045, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 12040, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 6784, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 3439, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 4790, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 3255, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 3517, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 5247, SeatsWonDirectly : 0}]},
        {Partyname: "Piraten", SecondaryVotes : 5147, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 458, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 442, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 652, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 373, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 323, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 443, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 506, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 328, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 412, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 354, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 528, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 328, SeatsWonDirectly : 0}]},          
    ]}    