const data_2011 = {
    SecondaryVotesTotalPlusOthers : 1461185,
    Parties : [ 
        {Partyname: "SPD", SecondaryVotes : 413332, SeatsWonDirectly : 33, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 31057, SeatsWonDirectly : 4}, 
            {DistrictNumber: "02", SecondaryVotes : 25107, SeatsWonDirectly : 1},
            {DistrictNumber: "03", SecondaryVotes : 49388, SeatsWonDirectly : 7},
            {DistrictNumber: "04", SecondaryVotes : 43323, SeatsWonDirectly : 4},
            {DistrictNumber: "05", SecondaryVotes : 29294, SeatsWonDirectly : 3},
            {DistrictNumber: "06", SecondaryVotes : 37507, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 39643, SeatsWonDirectly : 4},
            {DistrictNumber: "08", SecondaryVotes : 30752, SeatsWonDirectly : 1},
            {DistrictNumber: "09", SecondaryVotes : 34452, SeatsWonDirectly : 6},
            {DistrictNumber: "10", SecondaryVotes : 28636, SeatsWonDirectly : 1},
            {DistrictNumber: "11", SecondaryVotes : 33107, SeatsWonDirectly : 2},
            {DistrictNumber: "12", SecondaryVotes : 31066, SeatsWonDirectly : 0}]},
        {Partyname: "CDU", SecondaryVotes : 341158, SeatsWonDirectly : 25, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 19348, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 8785, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 23448, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 39169, SeatsWonDirectly : 3},
            {DistrictNumber: "05", SecondaryVotes : 31652, SeatsWonDirectly : 2},
            {DistrictNumber: "06", SecondaryVotes : 54140, SeatsWonDirectly : 7},
            {DistrictNumber: "07", SecondaryVotes : 42369, SeatsWonDirectly : 3},
            {DistrictNumber: "08", SecondaryVotes : 29888, SeatsWonDirectly : 3},
            {DistrictNumber: "09", SecondaryVotes : 18975, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 17780, SeatsWonDirectly : 1},
            {DistrictNumber: "11", SecondaryVotes : 13182, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 42422, SeatsWonDirectly : 6},]},
        {Partyname: "Grüne", SecondaryVotes : 257063, SeatsWonDirectly : 11, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 24331, SeatsWonDirectly : 1},
            {DistrictNumber: "02", SecondaryVotes : 31748, SeatsWonDirectly : 5},
            {DistrictNumber: "03", SecondaryVotes : 32369, SeatsWonDirectly : 2},
            {DistrictNumber: "04", SecondaryVotes : 30142, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 11538, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 31536, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 33621, SeatsWonDirectly : 1},
            {DistrictNumber: "08", SecondaryVotes : 20018, SeatsWonDirectly : 2},
            {DistrictNumber: "09", SecondaryVotes : 12813, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 5732, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 8128, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 15087, SeatsWonDirectly : 0},]},
        {Partyname: "Linke", SecondaryVotes : 171050, SeatsWonDirectly : 9, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 11891, SeatsWonDirectly : 1},
            {DistrictNumber: "02", SecondaryVotes : 13590, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 30354, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 5015, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 3454, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 4512, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 5891, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 6320, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 27408, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 27863, SeatsWonDirectly : 4},
            {DistrictNumber: "11", SecondaryVotes : 31076, SeatsWonDirectly : 4},
            {DistrictNumber: "12", SecondaryVotes : 3676, SeatsWonDirectly : 0},]},
        {Partyname: "AfD", SecondaryVotes : 0, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 0, SeatsWonDirectly : 0},]},
        {Partyname: "FDP", SecondaryVotes : 26943, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 1880, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 1043, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 2158, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 4196, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 1900, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 4533, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 2984, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 2013, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 1395, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 1314, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 936, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 2591, SeatsWonDirectly : 0}]},
        {Partyname: "Piraten", SecondaryVotes : 130105, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 11333, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 15387, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 17767, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 9721, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 6798, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 9600, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 11360, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 10760, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 11129, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 8901, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 9941, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 7408, SeatsWonDirectly : 0}]},          
    ]}    