const data_2023 = {
    SecondaryVotesTotalPlusOthers : 1516860,
    Parties : [ 
        {Partyname: "SPD", SecondaryVotes : 279017, SeatsWonDirectly : 4, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 19746, SeatsWonDirectly : 0}, 
            {DistrictNumber: "02", SecondaryVotes : 15682, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 30464, SeatsWonDirectly : 1},
            {DistrictNumber: "04", SecondaryVotes : 29232, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 19002, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 30587, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 29421, SeatsWonDirectly : 1},
            {DistrictNumber: "08", SecondaryVotes : 23535, SeatsWonDirectly : 1},
            {DistrictNumber: "09", SecondaryVotes : 23446, SeatsWonDirectly : 1},
            {DistrictNumber: "10", SecondaryVotes : 17456, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 18958, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 21488, SeatsWonDirectly : 0}]},
        {Partyname: "CDU", SecondaryVotes : 428228, SeatsWonDirectly : 48, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 24131, SeatsWonDirectly : 2},
            {DistrictNumber: "02", SecondaryVotes : 14317, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 40499, SeatsWonDirectly : 3},
            {DistrictNumber: "04", SecondaryVotes : 43134, SeatsWonDirectly : 6},
            {DistrictNumber: "05", SecondaryVotes : 34531, SeatsWonDirectly : 5},
            {DistrictNumber: "06", SecondaryVotes : 53572, SeatsWonDirectly : 7},
            {DistrictNumber: "07", SecondaryVotes : 45975, SeatsWonDirectly : 4},
            {DistrictNumber: "08", SecondaryVotes : 31101, SeatsWonDirectly : 3},
            {DistrictNumber: "09", SecondaryVotes : 33911, SeatsWonDirectly : 4},
            {DistrictNumber: "10", SecondaryVotes : 34847, SeatsWonDirectly : 4},
            {DistrictNumber: "11", SecondaryVotes : 29591, SeatsWonDirectly : 4},
            {DistrictNumber: "12", SecondaryVotes : 42617, SeatsWonDirectly : 6},]},
        {Partyname: "Grüne", SecondaryVotes : 278964, SeatsWonDirectly : 20, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 32445, SeatsWonDirectly : 5},
            {DistrictNumber: "02", SecondaryVotes : 35905, SeatsWonDirectly : 5},
            {DistrictNumber: "03", SecondaryVotes : 42410, SeatsWonDirectly : 5},
            {DistrictNumber: "04", SecondaryVotes : 30419, SeatsWonDirectly : 1},
            {DistrictNumber: "05", SecondaryVotes : 8935, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 27876, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 32098, SeatsWonDirectly : 2},
            {DistrictNumber: "08", SecondaryVotes : 20509, SeatsWonDirectly : 2},
            {DistrictNumber: "09", SecondaryVotes : 15930, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 6056, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 13689, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 12692, SeatsWonDirectly : 0},]},
        {Partyname: "Linke", SecondaryVotes : 185119, SeatsWonDirectly : 4, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 18898, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 22558, SeatsWonDirectly : 1},
            {DistrictNumber: "03", SecondaryVotes : 30465, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 10834, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 3989, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 8324, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 12567, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 14522, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 20670, SeatsWonDirectly : 1},
            {DistrictNumber: "10", SecondaryVotes : 15832, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 21655, SeatsWonDirectly : 2},
            {DistrictNumber: "12", SecondaryVotes : 4805, SeatsWonDirectly : 0},]},
        {Partyname: "AfD", SecondaryVotes : 137871, SeatsWonDirectly : 2, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 6720, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 3935, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 17977, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 7439, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 9712, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 8665, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 9264, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 8325, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 18090, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 20999, SeatsWonDirectly : 2},
            {DistrictNumber: "11", SecondaryVotes : 16115, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 10630, SeatsWonDirectly : 0},]},
        {Partyname: "FDP", SecondaryVotes : 70416, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 6062, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 3558, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 7351, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 10324, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 4045, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 12043, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 6780, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 3437, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 4790, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 3253, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 3526, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 5247, SeatsWonDirectly : 0}]},
        {Partyname: "Piraten", SecondaryVotes : 5145, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 458, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 442, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 653, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 374, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 318, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 442, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 509, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 328, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 412, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 353, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 528, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 328, SeatsWonDirectly : 0}]},          
    ]}    