const data_empty = {
    SecondaryVotesTotalPlusOthers : 0,
    Parties : [ 
        {Partyname: "SPD", SecondaryVotes : 0, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 0, SeatsWonDirectly : 0}, 
            {DistrictNumber: "02", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 0, SeatsWonDirectly : 0}]},
        {Partyname: "CDU", SecondaryVotes : 0, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 0, SeatsWonDirectly : 0},]},
        {Partyname: "Grüne", SecondaryVotes : 0, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 0, SeatsWonDirectly : 0},]},
        {Partyname: "Linke", SecondaryVotes : 0, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 0, SeatsWonDirectly : 0},]},
        {Partyname: "AfD", SecondaryVotes : 0, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 0, SeatsWonDirectly : 0},]},
        {Partyname: "FDP", SecondaryVotes : 0, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 0, SeatsWonDirectly : 0}]},
        {Partyname: "Piraten", SecondaryVotes : 0, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 0, SeatsWonDirectly : 0}]},          
    ]}    