const data_2006 = {
    SecondaryVotesTotalPlusOthers : 1377355,
    Parties : [ 
        {Partyname: "SPD", SecondaryVotes : 424054, SeatsWonDirectly : 40, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 33073, SeatsWonDirectly : 5}, 
            {DistrictNumber: "02", SecondaryVotes : 27295, SeatsWonDirectly : 1},
            {DistrictNumber: "03", SecondaryVotes : 45742, SeatsWonDirectly : 7},
            {DistrictNumber: "04", SecondaryVotes : 46637, SeatsWonDirectly : 6},
            {DistrictNumber: "05", SecondaryVotes : 30401, SeatsWonDirectly : 4},
            {DistrictNumber: "06", SecondaryVotes : 40199, SeatsWonDirectly : 2},
            {DistrictNumber: "07", SecondaryVotes : 44064, SeatsWonDirectly : 5},
            {DistrictNumber: "08", SecondaryVotes : 32748, SeatsWonDirectly : 3},
            {DistrictNumber: "09", SecondaryVotes : 34561, SeatsWonDirectly : 6},
            {DistrictNumber: "10", SecondaryVotes : 26618, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 28833, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 33883, SeatsWonDirectly : 1}]},
        {Partyname: "CDU", SecondaryVotes : 294026, SeatsWonDirectly : 19, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 17360, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 7869, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 17556, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 36003, SeatsWonDirectly : 1},
            {DistrictNumber: "05", SecondaryVotes : 28389, SeatsWonDirectly : 1},
            {DistrictNumber: "06", SecondaryVotes : 45835, SeatsWonDirectly : 5},
            {DistrictNumber: "07", SecondaryVotes : 38277, SeatsWonDirectly : 3},
            {DistrictNumber: "08", SecondaryVotes : 29855, SeatsWonDirectly : 3},
            {DistrictNumber: "09", SecondaryVotes : 13758, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 12658, SeatsWonDirectly : 1},
            {DistrictNumber: "11", SecondaryVotes : 9355, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 37111, SeatsWonDirectly : 5},]},
        {Partyname: "Grüne", SecondaryVotes : 180865, SeatsWonDirectly : 5, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 17442, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 24142, SeatsWonDirectly : 3},
            {DistrictNumber: "03", SecondaryVotes : 23924, SeatsWonDirectly : 2},
            {DistrictNumber: "04", SecondaryVotes : 22472, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 7522, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 22736, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 23961, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 11793, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 7531, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 4194, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 5121, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 10027, SeatsWonDirectly : 0},]},
        {Partyname: "Linke", SecondaryVotes : 185185, SeatsWonDirectly : 14, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 12921, SeatsWonDirectly : 1},
            {DistrictNumber: "02", SecondaryVotes : 15188, SeatsWonDirectly : 1},
            {DistrictNumber: "03", SecondaryVotes : 33528, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 5036, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 3417, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 4404, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 5643, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 5257, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 29913, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 31426, SeatsWonDirectly : 6},
            {DistrictNumber: "11", SecondaryVotes : 34890, SeatsWonDirectly : 6},
            {DistrictNumber: "12", SecondaryVotes : 3562, SeatsWonDirectly : 0},]},
        {Partyname: "AfD", SecondaryVotes : 0, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 0, SeatsWonDirectly : 0},]},
        {Partyname: "FDP", SecondaryVotes : 104584, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 6976, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 3696, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 7537, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 14173, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 7776, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 18342, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 13029, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 8039, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 5488, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 4625, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 4127, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 10776, SeatsWonDirectly : 0}]},
        {Partyname: "Piraten", SecondaryVotes : 0, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 0, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 0, SeatsWonDirectly : 0}]},          
    ]}    