const data_2021 = {
    SecondaryVotesTotalPlusOthers : 1821664,
    Parties : [ 
        {Partyname: "SPD", SecondaryVotes : 390329, SeatsWonDirectly : 25, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 27895, SeatsWonDirectly : 2}, 
            {DistrictNumber: "02", SecondaryVotes : 19766, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 40281, SeatsWonDirectly : 3},
            {DistrictNumber: "04", SecondaryVotes : 37651, SeatsWonDirectly : 2},
            {DistrictNumber: "05", SecondaryVotes : 28226, SeatsWonDirectly : 3},
            {DistrictNumber: "06", SecondaryVotes : 39529, SeatsWonDirectly : 1},
            {DistrictNumber: "07", SecondaryVotes : 39576, SeatsWonDirectly : 2},
            {DistrictNumber: "08", SecondaryVotes : 37228, SeatsWonDirectly : 4},
            {DistrictNumber: "09", SecondaryVotes : 33802, SeatsWonDirectly : 5},
            {DistrictNumber: "10", SecondaryVotes : 26545, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 30132, SeatsWonDirectly : 1},
            {DistrictNumber: "12", SecondaryVotes : 29698, SeatsWonDirectly : 2}]},
        {Partyname: "CDU", SecondaryVotes : 328587, SeatsWonDirectly : 21, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 18315, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 9917, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 27784, SeatsWonDirectly : 1},
            {DistrictNumber: "04", SecondaryVotes : 34936, SeatsWonDirectly : 2},
            {DistrictNumber: "05", SecondaryVotes : 29178, SeatsWonDirectly : 2},
            {DistrictNumber: "06", SecondaryVotes : 44265, SeatsWonDirectly : 5},
            {DistrictNumber: "07", SecondaryVotes : 36069, SeatsWonDirectly : 2},
            {DistrictNumber: "08", SecondaryVotes : 22207, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 22230, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 28140, SeatsWonDirectly : 3},
            {DistrictNumber: "11", SecondaryVotes : 19872, SeatsWonDirectly : 2},
            {DistrictNumber: "12", SecondaryVotes : 35674, SeatsWonDirectly : 4},]},
        {Partyname: "Grüne", SecondaryVotes : 343871, SeatsWonDirectly : 24, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 39032, SeatsWonDirectly : 5},
            {DistrictNumber: "02", SecondaryVotes : 42374, SeatsWonDirectly : 5},
            {DistrictNumber: "03", SecondaryVotes : 50990, SeatsWonDirectly : 5},
            {DistrictNumber: "04", SecondaryVotes : 37882, SeatsWonDirectly : 3},
            {DistrictNumber: "05", SecondaryVotes : 12749, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 34524, SeatsWonDirectly : 1},
            {DistrictNumber: "07", SecondaryVotes : 38517, SeatsWonDirectly : 3},
            {DistrictNumber: "08", SecondaryVotes : 24147, SeatsWonDirectly : 2},
            {DistrictNumber: "09", SecondaryVotes : 20349, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 9064, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 17509, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 16734, SeatsWonDirectly : 0},]},
        {Partyname: "Linke", SecondaryVotes : 256063, SeatsWonDirectly : 6, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 26063, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 30997, SeatsWonDirectly : 1},
            {DistrictNumber: "03", SecondaryVotes : 40810, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 14372, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 6162, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 10814, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 17034, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 19624, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 29168, SeatsWonDirectly : 1},
            {DistrictNumber: "10", SecondaryVotes : 24202, SeatsWonDirectly : 1},
            {DistrictNumber: "11", SecondaryVotes : 30044, SeatsWonDirectly : 3},
            {DistrictNumber: "12", SecondaryVotes : 6773, SeatsWonDirectly : 0},]},
        {Partyname: "AfD", SecondaryVotes : 145712, SeatsWonDirectly : 2, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 7260, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 4128, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 17355, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 7935, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 10978, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 9158, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 10207, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 9610, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 18586, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 21847, SeatsWonDirectly : 2},
            {DistrictNumber: "11", SecondaryVotes : 16888, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 11760, SeatsWonDirectly : 0},]},
        {Partyname: "FDP", SecondaryVotes : 130201, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 10618, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 6241, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 13461, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 17273, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 8514, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 19147, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 12819, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 6950, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 10331, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 7015, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 7761, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 10071, SeatsWonDirectly : 0}]},
        {Partyname: "Piraten", SecondaryVotes : 7440, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 663, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 655, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 938, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 516, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 465, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 636, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 689, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 483, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 650, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 602, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 779, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 364, SeatsWonDirectly : 0}]},
        ]}    