const data_2016 = {
    SecondaryVotesTotalPlusOthers : 1635169,
    Parties : [ 
        {Partyname: "SPD", SecondaryVotes : 352430, SeatsWonDirectly : 28, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 27172, SeatsWonDirectly : 4}, 
            {DistrictNumber: "02", SecondaryVotes : 21087, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 39583, SeatsWonDirectly : 5},
            {DistrictNumber: "04", SecondaryVotes : 34318, SeatsWonDirectly : 5},
            {DistrictNumber: "05", SecondaryVotes : 27740, SeatsWonDirectly : 3},
            {DistrictNumber: "06", SecondaryVotes : 34737, SeatsWonDirectly : 2},
            {DistrictNumber: "07", SecondaryVotes : 39427, SeatsWonDirectly : 3},
            {DistrictNumber: "08", SecondaryVotes : 29243, SeatsWonDirectly : 3},
            {DistrictNumber: "09", SecondaryVotes : 27720, SeatsWonDirectly : 3},
            {DistrictNumber: "10", SecondaryVotes : 20329, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 24950, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 26124, SeatsWonDirectly : 0}]},
        {Partyname: "CDU", SecondaryVotes : 287997, SeatsWonDirectly : 21, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 17076, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 9053, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 24719, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 30545, SeatsWonDirectly : 2},
            {DistrictNumber: "05", SecondaryVotes : 24835, SeatsWonDirectly : 2},
            {DistrictNumber: "06", SecondaryVotes : 41065, SeatsWonDirectly : 5},
            {DistrictNumber: "07", SecondaryVotes : 31622, SeatsWonDirectly : 2},
            {DistrictNumber: "08", SecondaryVotes : 22356, SeatsWonDirectly : 2},
            {DistrictNumber: "09", SecondaryVotes : 17502, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 20761, SeatsWonDirectly : 2},
            {DistrictNumber: "11", SecondaryVotes : 15223, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 33240, SeatsWonDirectly : 6},]},
        {Partyname: "Grüne", SecondaryVotes : 248324, SeatsWonDirectly : 12, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 26901, SeatsWonDirectly : 2},
            {DistrictNumber: "02", SecondaryVotes : 32778, SeatsWonDirectly : 4},
            {DistrictNumber: "03", SecondaryVotes : 35145, SeatsWonDirectly : 2},
            {DistrictNumber: "04", SecondaryVotes : 27822, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 8779, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 26976, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 29615, SeatsWonDirectly : 2},
            {DistrictNumber: "08", SecondaryVotes : 20308, SeatsWonDirectly : 2},
            {DistrictNumber: "09", SecondaryVotes : 12278, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 5346, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 9749, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 12627, SeatsWonDirectly : 0},]},
        {Partyname: "Linke", SecondaryVotes : 255701, SeatsWonDirectly : 12, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 22154, SeatsWonDirectly : 1},
            {DistrictNumber: "02", SecondaryVotes : 27016, SeatsWonDirectly : 1},
            {DistrictNumber: "03", SecondaryVotes : 42196, SeatsWonDirectly : 1},
            {DistrictNumber: "04", SecondaryVotes : 13922, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 6726, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 11152, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 15348, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 17017, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 30667, SeatsWonDirectly : 2},
            {DistrictNumber: "10", SecondaryVotes : 28216, SeatsWonDirectly : 2},
            {DistrictNumber: "11", SecondaryVotes : 34041, SeatsWonDirectly : 5},
            {DistrictNumber: "12", SecondaryVotes : 7246, SeatsWonDirectly : 0},]},
        {Partyname: "AfD", SecondaryVotes : 231492, SeatsWonDirectly : 5, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 12480, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 7396, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 27152, SeatsWonDirectly : 1},
            {DistrictNumber: "04", SecondaryVotes : 15431, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 16748, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 17677, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 18097, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 17294, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 27736, SeatsWonDirectly : 1},
            {DistrictNumber: "10", SecondaryVotes : 28310, SeatsWonDirectly : 2},
            {DistrictNumber: "11", SecondaryVotes : 24002, SeatsWonDirectly : 1},
            {DistrictNumber: "12", SecondaryVotes : 19169, SeatsWonDirectly : 0},]},
        {Partyname: "FDP", SecondaryVotes : 109500, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 8333, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 4517, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 8667, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 18454, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 7703, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 19051, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 12465, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 7209, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 5494, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 3411, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 3694, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 10502, SeatsWonDirectly : 0}]},
        {Partyname: "Piraten", SecondaryVotes : 28332, SeatsWonDirectly : 0, Districtdata: [
            {DistrictNumber: "01", SecondaryVotes : 2887, SeatsWonDirectly : 0},
            {DistrictNumber: "02", SecondaryVotes : 3629, SeatsWonDirectly : 0},
            {DistrictNumber: "03", SecondaryVotes : 3938, SeatsWonDirectly : 0},
            {DistrictNumber: "04", SecondaryVotes : 2003, SeatsWonDirectly : 0},
            {DistrictNumber: "05", SecondaryVotes : 1398, SeatsWonDirectly : 0},
            {DistrictNumber: "06", SecondaryVotes : 2242, SeatsWonDirectly : 0},
            {DistrictNumber: "07", SecondaryVotes : 2478, SeatsWonDirectly : 0},
            {DistrictNumber: "08", SecondaryVotes : 2427, SeatsWonDirectly : 0},
            {DistrictNumber: "09", SecondaryVotes : 2230, SeatsWonDirectly : 0},
            {DistrictNumber: "10", SecondaryVotes : 1573, SeatsWonDirectly : 0},
            {DistrictNumber: "11", SecondaryVotes : 2233, SeatsWonDirectly : 0},
            {DistrictNumber: "12", SecondaryVotes : 1294, SeatsWonDirectly : 0}]},            
    ]}    